#!/bin/bash

TEMP_OUTPUT=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader)
echo "${TEMP_OUTPUT}°C"
echo "${TEMP_OUTPUT}°C"

if [[ "${TEMP_OUTPUT}" -gt 90 ]]; then
    echo "#FF0000"
elif [[ "${TEMP_OUTPUT}" -lt 90 && "${TEMP_OUTPUT}" -gt 70 ]]; then
    echo "#FFAE00"
elif [[ "${TEMP_OUTPUT}" -lt 70 && "${TEMP_OUTPUT}" -gt 50 ]]; then
    echo "#FFF600"
elif [[ "${TEMP_OUTPUT}" -lt 50 ]]; then
    echo -e "#a8fcdf"
fi
